# -*- coding: utf-8 -*-
"""Fatal Police Shooting

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zg-tic0ZjTQSkN0YXI2CtB3ix9H---Fh
"""

import pandas as pd

df = pd.read_csv('database.csv')
df.head()

df.isnull()

df2 = df.dropna()
df2

df2.shape

# This tells me that majoirty of the deceased were between that ages of 20-40
df2['age'].plot.density();

df2['name'].unique

# Refining my search down
df3 = df2[['date', 'manner_of_death', 'armed', 'gender', 'race', 'signs_of_mental_illness']].copy()

df3

# Need to change 'date' from object to datetime
df3.dtypes

# Changed to date time
df3['date'] =  pd.to_datetime(df3['date'], format='%Y/%m/%d')

df3.dtypes

#Import datetime
# Choose a specific year

import datetime as dt

df3['date'] = pd.to_datetime(df3['date'])

df4 = df3[df3['date'].dt.year == 2016]

# New dataset
df4

fig = px.scatter_3d(df4, x='date', y='race', z='armed',
                    color='armed')
fig.show()

"""i am interested in looking at the mental health of the deceased and will be working my project around this."""

# Baseline
df4['signs_of_mental_illness'].value_counts(normalize=True)

"""Looking at the bar plot below, there is a minority of cases where the people were suffering from mental health issues"""

df4.signs_of_mental_illness.value_counts().plot.bar()

